sudo: required
dist: xenial
language: generic

branches:
  only:
    - master
    - melodic

compiler:
  - gcc

install:
  - export ROSDISTRO=kinetic
  - sudo apt-get update
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y dpkg
  - sudo apt-get install -y ros-$ROSDISTRO-ros-base
  - sudo apt-get install -y python-rosdep
  - sudo `which rosdep` init
  - rosdep update
  - rosdep install --default-yes --from-paths . --ignore-src --rosdistro $ROSDISTRO
  - source /opt/ros/$ROSDISTRO/setup.bash
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages

script: 
  - cd
  - git clone https://github.com/gssabu/gvac_install
  - cd gvac_install
  - ./install 2wd xv11 test

notifications:
  email:
    - godsownglists3@gmail.com
